name: 'test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - staging

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run test