name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging

jobs:
  test:
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm
      - name: Install
        run: npm install
      - name: Test
        run: npm run test